# Generated by Django 4.2.13 on 2026-05-19 16:19

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('wagtailcore', '0093_uploadedfile'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True, verbose_name='مقدمه')),
            ],
            options={
                'verbose_name': 'فهرست مقالات',
                'verbose_name_plural': 'فهرست مقالات',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='تاریخ انتشار')),
                ('intro', models.CharField(max_length=400, verbose_name='خلاصه مقاله')),
                ('author', models.CharField(blank=True, default='گوهر ولا', max_length=100, verbose_name='نویسنده')),
                ('body', wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='title', label='عنوان')), ('paragraph', wagtail.blocks.RichTextBlock(label='متن')), ('image', wagtail.images.blocks.ImageChooserBlock(label='تصویر')), ('quote', wagtail.blocks.StructBlock([('text', wagtail.blocks.TextBlock(label='متن نقل\u200cقول')), ('author', wagtail.blocks.CharBlock(label='گوینده', required=False))], label='نقل\u200cقول'))], verbose_name='محتوای مقاله')),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='تصویر شاخص')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', wagtail.fields.RichTextField(verbose_name='متن فوتر')),
            ],
            options={
                'verbose_name': 'متن فوتر',
                'verbose_name_plural': 'متن\u200cهای فوتر',
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('instagram', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('telegram', models.URLField(blank=True, verbose_name='تلگرام')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتس\u200cاپ')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='گوهر ولا', max_length=255, verbose_name='عنوان بنر')),
                ('hero_subtitle', models.CharField(blank=True, max_length=500, verbose_name='زیرعنوان بنر')),
                ('hero_button_text', models.CharField(default='مشاهده محصولات', max_length=100, verbose_name='متن دکمه بنر')),
                ('intro_text', wagtail.fields.RichTextField(blank=True, verbose_name='متن معرفی')),
                ('about_section', wagtail.fields.RichTextField(blank=True, verbose_name='درباره ما')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='تصویر بنر')),
            ],
            options={
                'verbose_name': 'صفحه اصلی',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='cms.blogpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='cms.BlogPageTag', to='taggit.Tag', verbose_name='برچسب\u200cها'),
        ),
    ]
