# Generated by Django 4.2.13 on 2026-06-09 23:51

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero_slider",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "slides",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        label="عنوان"
                                                    ),
                                                ),
                                                (
                                                    "subtitle",
                                                    wagtail.blocks.CharBlock(
                                                        label="زیرعنوان", required=False
                                                    ),
                                                ),
                                                (
                                                    "badge",
                                                    wagtail.blocks.CharBlock(
                                                        label="برچسب", required=False
                                                    ),
                                                ),
                                                (
                                                    "cta_text",
                                                    wagtail.blocks.CharBlock(
                                                        label="متن دکمه", required=False
                                                    ),
                                                ),
                                                (
                                                    "cta_link",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="مثال: /products",
                                                        label="لینک دکمه",
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "accent",
                                                    wagtail.blocks.CharBlock(
                                                        default="#b8860b",
                                                        label="رنگ تأکید (HEX)",
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        ),
                                        label="اسلایدها",
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "trust_bar",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "icon",
                                                    wagtail.blocks.ChoiceBlock(
                                                        choices=[
                                                            ("shield", "سپر / ضمانت"),
                                                            ("truck", "کامیون / ارسال"),
                                                            (
                                                                "rotate",
                                                                "بازگشت / مرجوعی",
                                                            ),
                                                            ("lock", "قفل / امنیت"),
                                                            (
                                                                "headphones",
                                                                "هدفون / پشتیبانی",
                                                            ),
                                                            ("gift", "هدیه"),
                                                            ("star", "ستاره"),
                                                            ("award", "مدال"),
                                                        ],
                                                        label="آیکن",
                                                    ),
                                                ),
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        label="عنوان"
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.CharBlock(
                                                        label="توضیح", required=False
                                                    ),
                                                ),
                                            ]
                                        ),
                                        label="موارد",
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "categories",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        default="دسته\u200cبندی محصولات", label="عنوان"
                                    ),
                                ),
                                (
                                    "subheading",
                                    wagtail.blocks.CharBlock(
                                        label="زیرعنوان", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "products",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "source",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("new", "جدیدترین محصولات"),
                                            ("bestsellers", "پرفروش\u200cترین محصولات"),
                                            ("featured", "محصولات ویژه"),
                                        ],
                                        label="منبع محصولات",
                                    ),
                                ),
                                ("heading", wagtail.blocks.CharBlock(label="عنوان")),
                                (
                                    "subheading",
                                    wagtail.blocks.CharBlock(
                                        label="زیرعنوان", required=False
                                    ),
                                ),
                                (
                                    "link_text",
                                    wagtail.blocks.CharBlock(
                                        default="مشاهده همه",
                                        label="متن لینک",
                                        required=False,
                                    ),
                                ),
                                (
                                    "link_url",
                                    wagtail.blocks.CharBlock(
                                        help_text="مثال: /products?ordering=-created_at",
                                        label="لینک",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "special_offer",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "badge",
                                    wagtail.blocks.CharBlock(
                                        label="برچسب", required=False
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(label="عنوان")),
                                (
                                    "description",
                                    wagtail.blocks.TextBlock(
                                        label="توضیح", required=False
                                    ),
                                ),
                                (
                                    "button_text",
                                    wagtail.blocks.CharBlock(
                                        label="متن دکمه", required=False
                                    ),
                                ),
                                (
                                    "button_link",
                                    wagtail.blocks.CharBlock(
                                        label="لینک دکمه", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "features",
                        wagtail.blocks.StructBlock(
                            [
                                ("heading", wagtail.blocks.CharBlock(label="عنوان")),
                                (
                                    "subheading",
                                    wagtail.blocks.CharBlock(
                                        label="زیرعنوان", required=False
                                    ),
                                ),
                                (
                                    "items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "icon",
                                                    wagtail.blocks.CharBlock(
                                                        help_text="مثال: 🏛️",
                                                        label="آیکن (اموجی)",
                                                    ),
                                                ),
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        label="عنوان"
                                                    ),
                                                ),
                                                (
                                                    "description",
                                                    wagtail.blocks.TextBlock(
                                                        label="توضیح"
                                                    ),
                                                ),
                                            ]
                                        ),
                                        label="ویژگی\u200cها",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "blog_preview",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.CharBlock(
                                        default="آخرین مطالب", label="عنوان"
                                    ),
                                ),
                                (
                                    "subheading",
                                    wagtail.blocks.CharBlock(
                                        label="زیرعنوان", required=False
                                    ),
                                ),
                                (
                                    "link_text",
                                    wagtail.blocks.CharBlock(
                                        default="مشاهده همه",
                                        label="متن لینک",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "newsletter",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(label="عنوان")),
                                (
                                    "description",
                                    wagtail.blocks.TextBlock(
                                        label="توضیح", required=False
                                    ),
                                ),
                                (
                                    "button_text",
                                    wagtail.blocks.CharBlock(
                                        default="عضویت",
                                        label="متن دکمه",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                help_text="هر بخش را می\u200cتوانید ویرایش، جابجا، اضافه یا حذف کنید.",
                verbose_name="بخش\u200cهای صفحه اصلی",
            ),
        ),
    ]
