# Generated by Django 4.2.13 on 2026-06-10 01:20

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_homepage_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "handle",
                    models.SlugField(
                        choices=[
                            ("main", "منوی اصلی (هدر)"),
                            ("footer_quick", "دسترسی سریع (فوتر)"),
                            ("footer_bottom", "لینک\u200cهای پایین (فوتر)"),
                        ],
                        help_text="تعیین می\u200cکند این منو کجای سایت نمایش داده شود.",
                        unique=True,
                        verbose_name="شناسه",
                    ),
                ),
            ],
            options={
                "verbose_name": "منو",
                "verbose_name_plural": "منوها",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("label", models.CharField(max_length=100, verbose_name="متن")),
                (
                    "link",
                    models.CharField(
                        help_text="مثال: /products یا /blog",
                        max_length=300,
                        verbose_name="لینک",
                    ),
                ),
                (
                    "open_in_new_tab",
                    models.BooleanField(
                        default=False, verbose_name="باز شدن در تب جدید"
                    ),
                ),
                (
                    "menu",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="cms.menu",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand_name",
                    models.CharField(
                        default="گوهر ولا", max_length=100, verbose_name="نام برند"
                    ),
                ),
                (
                    "brand_latin",
                    models.CharField(
                        blank=True,
                        default="GOHAREVELA",
                        max_length=100,
                        verbose_name="نام لاتین برند",
                    ),
                ),
                (
                    "brand_description",
                    models.TextField(blank=True, verbose_name="توضیح برند (فوتر)"),
                ),
                (
                    "phone_primary",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="تلفن ثابت"
                    ),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="تلفن همراه"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                ("address", models.TextField(blank=True, verbose_name="آدرس")),
                (
                    "working_hours",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="ساعت کاری"
                    ),
                ),
                ("instagram", models.URLField(blank=True, verbose_name="اینستاگرام")),
                ("telegram", models.URLField(blank=True, verbose_name="تلگرام")),
                ("whatsapp", models.URLField(blank=True, verbose_name="واتس\u200cاپ")),
                ("aparat", models.URLField(blank=True, verbose_name="آپارات")),
                (
                    "topbar_message",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="پیام نوار بالا"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
            },
        ),
        migrations.DeleteModel(
            name="SiteConfiguration",
        ),
    ]
