# Generated by Django 4.2.13 on 2026-06-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0003_menu_menuitem_sitesettings_delete_siteconfiguration"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "online_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="گزینه پرداخت آنلاین در سبد خرید نمایش داده شود.",
                        verbose_name="پرداخت آنلاین فعال",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("zarinpal", "زرین\u200cپال"),
                            ("idpay", "آی\u200cدی\u200cپی"),
                        ],
                        default="zarinpal",
                        max_length=20,
                        verbose_name="درگاه پرداخت",
                    ),
                ),
                (
                    "merchant_id",
                    models.CharField(
                        blank=True,
                        help_text="زرین\u200cپال: Merchant ID — آی\u200cدی\u200cپی: API Key",
                        max_length=200,
                        verbose_name="کد پذیرنده / API Key",
                    ),
                ),
                (
                    "sandbox",
                    models.BooleanField(
                        default=True,
                        help_text="در حالت آزمایشی پرداخت واقعی انجام نمی\u200cشود.",
                        verbose_name="حالت آزمایشی (Sandbox)",
                    ),
                ),
                (
                    "card_to_card_enabled",
                    models.BooleanField(default=True, verbose_name="کارت به کارت فعال"),
                ),
                (
                    "card_number",
                    models.CharField(
                        blank=True,
                        help_text="مثال: 6037-9970-XXXX-XXXX",
                        max_length=25,
                        verbose_name="شماره کارت",
                    ),
                ),
                (
                    "card_holder",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نام صاحب کارت"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات پرداخت",
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="نام روش ارسال"),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="توضیح"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        verbose_name="هزینه ارسال (تومان)",
                    ),
                ),
                (
                    "free_above",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="اگر مبلغ سبد از این رقم بیشتر باشد هزینه ارسال صفر می\u200cشود. ۰ یعنی ارسال رایگان نداریم.",
                        max_digits=12,
                        verbose_name="ارسال رایگان بالای (تومان)",
                    ),
                ),
                (
                    "estimated_days",
                    models.CharField(
                        blank=True,
                        help_text="مثال: ۳ تا ۵ روز کاری",
                        max_length=50,
                        verbose_name="زمان تحویل",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="ترتیب نمایش"
                    ),
                ),
            ],
            options={
                "verbose_name": "روش ارسال",
                "verbose_name_plural": "روش\u200cهای ارسال",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SmsSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(default=False, verbose_name="پیامک فعال"),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("kavenegar", "کاوه\u200cنگار"),
                            ("smsir", "اس\u200cام\u200cاس.آی\u200cآر"),
                        ],
                        default="kavenegar",
                        max_length=20,
                        verbose_name="سرویس پیامک",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="API Key"
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        blank=True,
                        help_text="در صورت داشتن خط اختصاصی وارد کنید.",
                        max_length=20,
                        verbose_name="شماره فرستنده",
                    ),
                ),
                (
                    "otp_template",
                    models.CharField(
                        blank=True,
                        help_text="نام قالب پیامک تأیید هویت (مثال: verify-code)",
                        max_length=100,
                        verbose_name="نام قالب OTP",
                    ),
                ),
                (
                    "order_confirm_template",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="نام قالب تأیید سفارش"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات پیامک",
            },
        ),
    ]
