# Generated by Django 4.2.13 on 2026-05-19 16:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(blank=True, upload_to='categories/', verbose_name='تصویر')),
                ('icon', models.CharField(blank=True, help_text='مثال: 💍', max_length=10, verbose_name='آیکن (اموجی)')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, max_length=320, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='توضیح کوتاه')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='قیمت (تومان)')),
                ('compare_price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='قیمت قبل از تخفیف (تومان)')),
                ('cost_price', models.DecimalField(blank=True, decimal_places=0, help_text='فقط برای مدیران قابل مشاهده است.', max_digits=12, null=True, verbose_name='قیمت تمام\u200cشده (تومان)')),
                ('sku', models.CharField(blank=True, max_length=100, unique=True, verbose_name='کد محصول (SKU)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='وزن کل (گرم)')),
                ('silver_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='وزن نقره (گرم)')),
                ('silver_grade', models.CharField(blank=True, choices=[('925', '925 – نقره استرلینگ'), ('835', '835 – نقره اروپایی'), ('999', '999 – نقره خالص')], max_length=3, verbose_name='عیار نقره')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه / پیشنهاد ویژه')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('out_of_stock', 'ناموجود')], default='active', max_length=20, verbose_name='وضعیت')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد بازدید')),
                ('sales_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد فروش')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان متا')),
                ('meta_description', models.TextField(blank=True, verbose_name='توضیحات متا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سنگ')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='اسلاگ')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('origin', models.CharField(blank=True, help_text='مثال: یمن، نیشابور', max_length=100, verbose_name='منشأ')),
                ('image', models.ImageField(blank=True, upload_to='stones/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نوع سنگ',
                'verbose_name_plural': 'انواع سنگ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, max_length=120, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'برچسب',
                'verbose_name_plural': 'برچسب\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='متن جایگزین')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='stone_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.stonetype', verbose_name='نوع سنگ'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='products.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان نظر')),
                ('body', models.TextField(verbose_name='متن نظر')),
                ('is_approved', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product', verbose_name='محصول')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر محصول',
                'verbose_name_plural': 'نظرات محصولات',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
